### ISSUE TITLE
Can `README.md` give an example of an implementation.

### ISSUE THREAD

**Issue by TheKing42** [tel/serv#2]
In [README.md](https://github.com/tel/serv/blob/master/README.md), this is a reference to `myImplementation`, but no definition given. I would find it useful it there was an example implementation of an `Impl`.

**Comment by tel** [comment]
Sure, I'll throw one in.

**Comment by tel** [comment]
Actually, at the moment, I'm going to sit on this one. The response building API is probably too much under flux.

**Comment by tel** [comment]
There's some relevant code examples in https://github.com/tel/serv/blob/master/app/TestServer.hs though

**Comment by tel** [comment]
Note that the usage examples have changed significantly in the most recent (`singletons`-ized) version.
