### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by aspidites** [tel/serv#8]
Just a place holder for discussion at this point, as I'll probably give it a shot tomorrow (Sunday 2/7/16). I do wonder if it's as simple as cleaning up the example code to bring it in line with the new implementation, or if the use of Singletons has any implications on the library's overall strategy?

**Comment by tel** [comment]
Singletons change the syntax a bit. Definitely take a look at the existing examples (they compile and are the basis for the existing test suite).

**Comment by tel** [comment]
Bit change is reflecting status codes!

**Comment by aspidites** [comment]
On a semi related note, coming from servant, the imports here are a bit unwieldy. Consider that I need two imports for servant:

```haskell
import Servant
import Servant.Server
```

Versus 6 in Serv:
```haskell
import Serv.Api
import Serv.Common
import qualified Serv.ContentType as Ct
import Serv.Header as H
import Serv.StatusCode as Sc
import Serv.Server

**Comment by tel** [comment]
That's a very good point. I'd like to have more conversation there. Could
you open a separate Issue?

**Comment by aspidites** [comment]
@tel created #9 to for imports. 

As for this issue, I have created an (incomplete PR), and will move conversation there. Pardon the fragmentation.

**Comment by tel** [comment]
No problem :)

**Comment by tel** [comment]
I think it's a good idea to have separate conversation discussing issues and potential changes anyway :)

**Comment by tel** [comment]
The READMEs have been scaled back a bit but now reflect the new style properly. I'm closing this for now.

**Comment by aspidites** [comment]
It'd be nice to also show a wai application serving that API. That or something like "See foo/bar/example.hs for a complete application which serves this style of API".

That said, accurate, bare bones readme is better than a complete tutorial that is obsolete, so it's an appreciated improvement.

**Comment by tel** [comment]
I can at least add that line at the moment. I intend to explain it more in the README for `serv-wai`.

**Comment by tel** [comment]
Ok! That's done now.
